# Generated by Django 4.2.3 on 2023-08-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_username', models.CharField(max_length=50)),
                ('to_username', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=150)),
                ('canal', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('to_user_read', models.BooleanField(default=False)),
                ('from_user_read', models.BooleanField(default=False)),
            ],
        ),
    ]
