# Generated by Django 4.2.3 on 2023-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='from_user_read',
            field=models.BooleanField(default=True),
        ),
    ]
